### ISSUE TITLE
Any item can be put into the input/output slots of machines

### ISSUE THREAD

**Issue by dogboy21** [UnhappyCodings/thoriumreactors#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It is possible to put any item into the output slot of machines that produce items (for example the Fluid Evaporator).
It is also possible to put any item into the input slot of machines although they only accept one specific item.

### Multiplayer?

Multiplayer

### Operating System?

Windows

### Version

other

### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Links

https://u.dogboy.xyz/262RwByk.png
https://u.dogboy.xyz/nrELrgbv.png

**Comment by UnhappyCodings** [comment]
Hey! Thanks for your report! Will be fixed in ThoriumReactors 0.1.5r!
