### ISSUE TITLE
Crafting with right-click only yields half of the output amount

### ISSUE THREAD

**Issue by dogboy21** [UnhappyCodings/thoriumreactors#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When crafting a recipe in the Thorium Crafting Table that yields more than 1 item, taking the results out with a right click only gives half of the output amount.

### Multiplayer?

Multiplayer

### Operating System?

Windows

### Version

other

### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Links

https://u.dogboy.xyz/NXCPvEPw.gif

**Comment by UnhappyCodings** [comment]
Hey! Thanks for your report! Will be fixed in ThoriumReactors 0.1.5r!
