### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by 177unneh** [UnhappyCodings/thoriumreactors#13]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

So idk what, but 
![image](https://github.com/IntelligenceModding/thoriumreactors/assets/78876688/fc52e05c-19d1-4121-8092-42e879fd5d09)
well. There are missing textures :V

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

0.1.5b

### Minecraft Version

1.20.1

### Forge Version

47.2.0

**Comment by UnhappyCodings** [comment]
Hey! Could you please update your Fusion to the newest version?

**Comment by 177unneh** [comment]
it is the newest version

**Comment by UnhappyCodings** [comment]
Are you sure you have the right fusion mod installed? There are two, one adds furnaces, the other one connected textures. 
Use this link to download the latest version please. I had the exact same issue on discord already!
https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures/files?page=1&pageSize=20&version=1.20.1

**Comment by 177unneh** [comment]
yeah i mistaken the mod with the other mod with furnaces. Maybe add it in to description of the mod? Anyway thanks

**Comment by UnhappyCodings** [comment]
Yeah, already did that in dev environment!

**Comment by Korenchkin** [comment]
hello,sorry to necro this,this info is really hard to find,so maybe my comment makes it more visible? i'm really happy this mod exists and have to try it,so i hope it stays alive for new versions too (when new mc versions are viable with other mods)!thank you!
