### ISSUE TITLE
Add tags to ores for better compat

### ISSUE THREAD

**Issue by HydrogenC** [UnhappyCodings/thoriumreactors#14]
### Description

Now the ores doesn't have forge oredict tags, so that they cannot be identified by other ore processing mods (e.g. Mekanism) and I can only process it with the vanilla furnace. Please add tags to them in order to have better mod compat.

**Comment by UnhappyCodings** [comment]
Hey! Looks like I forgot to add even more tags for mekanism compatibility. Will do that soon.

**Comment by UnhappyCodings** [comment]
Hey! Just uploaded 0.1.6b where its fixed! Hope I got all this time.
