### ISSUE TITLE
Reactor eats Uran but it said that id dont have any.

### ISSUE THREAD

**Issue by 177unneh** [UnhappyCodings/thoriumreactors#15]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description

And here im again.

So i gived reactor a uran and, he eated it, but is still saing that the dont have any, and this time it dont want to get more.
![2024-01-20_10 34 04](https://github.com/IntelligenceModding/thoriumreactors/assets/78876688/6473985e-a2fc-4f81-8d59-950fba628e53)
![2024-01-20_10 34 13](https://github.com/IntelligenceModding/thoriumreactors/assets/78876688/8cc149ac-9ea8-4bc4-94d9-1f489166fbaa)
![2024-01-20_10 34 21](https://github.com/IntelligenceModding/thoriumreactors/assets/78876688/e496f19a-cca0-46e3-a7c8-6c36e98fda2f)
![2024-01-20_10 34 24](https://github.com/IntelligenceModding/thoriumreactors/assets/78876688/51e42145-0262-4bbd-8cf0-5281341e0ba8)

Idk what im doing wrong, i created another reactor and this same problem

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

other

### Minecraft Version

1.20.1

### Forge Version

47.2.0

**Comment by UnhappyCodings** [comment]
Hey! You did not set your "Fuel Load", left screen in the middle, to any value from 0-100%. The 64 "eatem" uranium are just in the valve, dont worry ^^

**Comment by 177unneh** [comment]
AHH! Im so stupid XD. Anyway thanks you!
