### ISSUE TITLE
Thermal heat exchanger

### ISSUE THREAD

**Issue by MCGAMER27** [UnhappyCodings/thoriumreactors#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i connected the thorium reactor too the heat exchanger but the heated molten salt is not going in too broduce steam. i did
evrything like you wrote but it doesnt work

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

0.1a

### Minecraft Version

1.20.1

### Forge Version

47.2.20

**Comment by UnhappyCodings** [comment]
Hey! Can you please check if you set each valve to the right configuration type and you used real minecraft water not some fake water by external mods (Just had that case). Otherwise please send me some pictures of your construction

**Comment by MCGAMER27** [comment]
![2024-01-23_23 34 03](https://github.com/IntelligenceModding/thoriumreactors/assets/63550184/f0d27d97-4a47-4cc8-8e09-37af59a5d783)
![2024-01-23_23 34 10](https://github.com/IntelligenceModding/thoriumreactors/assets/63550184/1b116fe6-f076-43df-aae0-7874b613024f)
![2024-01-23_23 33 49](https://github.com/IntelligenceModding/thoriumreactors/assets/63550184/b8f2b094-da80-4e1e-b224-f6480916a051)

**Comment by MCGAMER27** [comment]
wow thx for the help

**Comment by UnhappyCodings** [comment]
Hey! Im still a person who lives and has a real social life.
However, could you provide me more informations?
Please look at each of the valves and enter following command, then send me the text in chat in here!
/data get block <coordinatesOfBlock> (For coordinates just take the autocompletion)

**Comment by MCGAMER27** [comment]
it is working now but the turbine is not getting the steam

**Comment by UnhappyCodings** [comment]
Is the turbine assembled? Did you add the turbine to the reactor controller using a configurator. Did you set the flowrate then? ^^

**Comment by MCGAMER27** [comment]
yes i did all of that but the steam does not go in

**Comment by UnhappyCodings** [comment]
Hey! Are you still in need of help? Greetings

**Comment by UnhappyCodings** [comment]
No reply from you for 2 weeks, will close this Issue for now!
