### ISSUE TITLE
Breaking turbine rotor with turbine blades dont drop turbine blades

### ISSUE THREAD

**Issue by DevDyna** [UnhappyCodings/thoriumreactors#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

How to reproduce:
- Place a turbine rotor
- Click on it with one or more turbine blades
- Break it on survival with a pickaxe (like netherite)

You can see that rotor was dropped without any turbine blades

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

0.1.5b-all

### Minecraft Version

1.19.2

### Forge Version

43.3.7

**Comment by UnhappyCodings** [comment]
Hey! Thanks for your report, will look into that right now.

**Comment by UnhappyCodings** [comment]
Hey! Just uploaded 0.1.6b where I fixed this! Thanks for your report!
