### ISSUE TITLE
Recipes should have item tags as ingredient

### ISSUE THREAD

**Issue by DevDyna** [UnhappyCodings/thoriumreactors#18]
### Description

Playing with nuclearcraft and thorium reactor on same lets play i have find that thorium crafting table dont allow other graphite ingots so why not change as `#forge:ingots/graphite` to add compatibility ?

![2024-02-21_13 33 49](https://github.com/IntelligenceModding/thoriumreactors/assets/78147916/291cc9e4-2011-46e2-981e-47d2513345d4)

![2024-02-21_13 33 54](https://github.com/IntelligenceModding/thoriumreactors/assets/78147916/fde9ea97-d45b-46d1-a9c3-c1f854b26ff0)

**Comment by UnhappyCodings** [comment]
Hey! That's already planned for a pretty long time now. I made a mistake in Not adding Tag Support to all of my recipes, also machines. That rework will take a bit of time to complete and currently I dont see when I could finish it. Maybe next month.

**Comment by UnhappyCodings** [comment]
Its me again, took some of my time to remake almost all recipes to support external items and blocks. This will be fixed in 0.1.6b! But still no ETA, maybe next week :)

**Comment by UnhappyCodings** [comment]
Hey! Just uploaded 0.1.6b where I changed all this! Thanks for this Issue and if you still have problems or ideas regarding the crafting system just let me know!
