### ISSUE TITLE
Reactor Gui send client on crash -> mouseClicked event handler

### ISSUE THREAD

**Issue by DevDyna** [UnhappyCodings/thoriumreactors#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have try to add the mod on my modpack to "test the feature" and i have found that after builded the [reactor](https://docs.thorium-reactors.de/reactor/#reactor) as it was made , after builded and see particles i have pressed when opened the gui one of little boxes on the gui and directly it send me on crash client 
(reactor still empty on status off , literally fresh builded)

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

other

### Minecraft Version

1.19.2

### Forge Version

0.1.2b-all

### Links

[logs still long due a counter on game]
[latest.log](https://github.com/UnhappyCodings/thoriumreactors/files/13226490/latest.log)
[crash-2023-11-01_12.38.02-client.txt](https://github.com/UnhappyCodings/thoriumreactors/files/13226491/crash-2023-11-01_12.38.02-client.txt)

**Comment by UnhappyCodings** [comment]
Thanks, will investigate this!

**Comment by UnhappyCodings** [comment]
Should be fixed now! Thanks for reporting.
If anything still happens please open a new Issue or respond to this one!
