### ISSUE TITLE
[BUG] Depleted molten salt bucket and fluid issue

### ISSUE THREAD

**Issue by DevDyna** [UnhappyCodings/thoriumreactors#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![3-12-2024 (00-35-56)](https://github.com/IntelligenceModding/thoriumreactors/assets/78147916/3723587f-ca1b-4ce6-897e-7edbe636d25e)

# How to reproduce:
- place using /setblock a depleted molten salt

## A few of info that i have notify before it but i think that still as same issue :

- thermal expansion fluid encapsulator have same item bucket as result of molten salt and depleted molten salt (i dont have touched it)

![image](https://github.com/IntelligenceModding/thoriumreactors/assets/78147916/f1d68426-9ea6-4132-9fa5-6eaf66ddf590)

- *(like how i have try on the gif)*  if clicked with depleted molten salt bucket or molten salt bucket they return molten salt

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

other

### Minecraft Version

1.19.2

### Forge Version

43.3.7

**Comment by UnhappyCodings** [comment]
Hey! Thank you for your report. I found the problem and will fix it in the next version of Thorium! Have a nice day
