### ISSUE TITLE
Raw traslation string as name on Jade of any fluids when placed on world

### ISSUE THREAD

**Issue by DevDyna** [UnhappyCodings/thoriumreactors#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

minor issue
[screen below]

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

other

### Minecraft Version

1.19.2

### Forge Version

0.1.2b-all

### Links

![2023-11-01_16 59 41](https://github.com/UnhappyCodings/thoriumreactors/assets/78147916/84dc4ccf-4a79-4afc-a736-e8be17fb74fb)

**Comment by UnhappyCodings** [comment]
Thank you for reporting! Will take a look at that :D

**Comment by UnhappyCodings** [comment]
Took a look and found the problem, will be fixed in 0.1.3b. Thanks
