### ISSUE TITLE
Recipe conflict with JAOPCA and Mekanism

### ISSUE THREAD

**Issue by odessadraekavik** [UnhappyCodings/thoriumreactors#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Issue Type:** Bug

**Version:** 0.1.3.1b

**Environment:** Test

**Minecraft Version:** 1.19.2

**Forge Version:** 43.3.0

**Mods:**
![https://cdn.discordapp.com/attachments/1165024312680529942/1170718863143485490/image.png?ex=655a0fe7&is=65479ae7&hm=d00f632520c25acfcc980c6d168cdf4fd218b358cad144920ae6104435f6bc3a&](https://cdn.discordapp.com/attachments/1165024312680529942/1170718863143485490/image.png?ex=655a0fe7&is=65479ae7&hm=d00f632520c25acfcc980c6d168cdf4fd218b358cad144920ae6104435f6bc3a&)
-   JAPOCA 4.2.8.19
-   JEI 11.6.0.1018
-   Mekanism 10.3.9.13
-   Thorium Reactors 0.1.3.1b

**Problem:**

When trying to enrich Mekanism Fluorite Ore in the Mekanism Enrichment Chamber, the expected output of 6 Fluorite Crystals is instead replaced with 2 Fluorite Dusts.

**Steps to Reproduce:**

1.  Place a Mekanism Enrichment Chamber.
2.  Insert Mekanism Fluorite Ore into the input slot.
3.  Observe the output.

**Expected Output:**

6 Fluorite Crystals

**Actual Output:**

2 Fluorite Dusts

**Additional Information:**

Looking at the recipe usages for Fluorite Ore in JEI, there are two recipes for the same block. This suggests that there is a recipe conflict.

**Images:**

-   Mekanism Enrichment Chamber with Fluorite Dust output: ![https://cdn.discordapp.com/attachments/1165024312680529942/1170718998258786434/image.png?ex=655a1008&is=65479b08&hm=096db84e093b94aa2032836d2f175c1f1e9330abafc597ca1c3774f2030d0a45&](https://cdn.discordapp.com/attachments/1165024312680529942/1170718998258786434/image.png?ex=655a1008&is=65479b08&hm=096db84e093b94aa2032836d2f175c1f1e9330abafc597ca1c3774f2030d0a45&)
-   Mekanism Fluorite Ore and recipe usage showing two recipes for the same block: ![https://cdn.discordapp.com/attachments/1165024312680529942/1170718955330093147/image.png?ex=655a0ffd&is=65479afd&hm=17f88c94e8734f9c159afbbb202ae32f25f5aa31fa1d77d6390414fe509bdea4](https://cdn.discordapp.com/attachments/1165024312680529942/1170718955330093147/image.png?ex=655a0ffd&is=65479afd&hm=17f88c94e8734f9c159afbbb202ae32f25f5aa31fa1d77d6390414fe509bdea4)

**Notes:**

-   We are not sure if the issue is coming from JAOPCA or Thorium Reactors.
-   We have tested this issue with no other mods installed (Beside Mekanism and JAOPCA) and the issue still occurs.

We appreciate any help you can provide in resolving this issue.

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

0.1a

### Minecraft Version

1.19.2

### Forge Version

3.3.0

**Comment by UnhappyCodings** [comment]
Hey!
Thanks, will look into it as soon as possible! 
At first look it doesnt seem to come from me, since I dont have any integrations for mekanism!

**Comment by F0x06** [comment]
Hi,

juste to update i talked with creator of JAOPCA, and he gived a fix, still not sure where this sould be fixed

![image](https://github.com/UnhappyCodings/thoriumreactors/assets/7167311/8b0dc026-7a5c-49d3-9f6e-62f42cb3a4ac)

**Comment by UnhappyCodings** [comment]
Alright, so doesnt seem to come from my mod like i thought. 
This can only be fixed by modpack creators. I will close this error by now!
Thank you for reporting it any have a great day! :)
