### ISSUE TITLE
Recipe Tagging

### ISSUE THREAD

**Issue by LKD-PIX** [UnhappyCodings/thoriumreactors#5]
### Description

All the recipes and machines in the mod are not taking items from other mods for uranium, salt, yellowcake, aluminum, chromium etc.

Also not all the mods items are tagged correctly for use in other mods, namely raw uranium, thorium for example:

GregTech & Electrodynamics: forge:raw_materials/thorium
GregTech, Electrodynamics, Mekanism, AdAstra: forge:ingots/steel
Nuclear Science: forge:yellow_cake_uranium

Would be really cool to be able to craft the mods items using other mod's and vice versa using your items in other mods!

**Comment by UnhappyCodings** [comment]
Hey! 
Firstly thanks for that idea, I already thought about that many times and never really got to an end.
But dont really wanted to add this to the mod so the mod is still some type of closed system and its not pushed by other simple mods.

I will think about adding this in the next update!

**Comment by LKD-PIX** [comment]
Hmm, i see your point, in that case maybe take a spin on the naming of the stuff, i don't think they have to be integrated it's just a bit jarring to have two of the same item (name-wise from different mods) not being interchangable

**Comment by UnhappyCodings** [comment]
Hey, its me again, thought much about that, I will add those tags in version 0.1.4b of ThoriumReactors.
