### ISSUE TITLE
Could you change the font ?

### ISSUE THREAD

**Issue by zirrsm322** [UnhappyCodings/thoriumreactors#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![C3OHE37CSHWU{~E{H~ZD~29](https://github.com/UnhappyCodings/thoriumreactors/assets/141705296/07157647-d1df-4b60-9cad-239c7a6ac6ad)
I have made a Chinese translate for mod, but it seems to a bit error, i think is the problem to font, may you change the font to other?
With my very pleasure 

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

0.1a

### Minecraft Version

1.19.2

### Forge Version

43.3.0

**Comment by zirrsm322** [comment]
[zh_cn.json](https://github.com/UnhappyCodings/thoriumreactors/files/13391619/zh_cn.json)

**Comment by UnhappyCodings** [comment]
Hey! 
Thank you for your post, already read through it last week, just didnt got to reply. I will take a look where the problem comes from, already have an idea! 
Is the language file finished? If yes, i can directly implement it in my code!

**Comment by zirrsm322** [comment]
> Hey! Thank you for your post, already read through it last week, just didnt got to reply. I will take a look where the problem comes from, already have an idea! Is the language file finished? If yes, i can directly implement it in my code!

I almost finished the translation work, it can read by people and almost understand it.
But becuz this font problem i changed some translations back to Eng.
I have changed some "single block" machine's words which are like "Idle""crystallization""concentration". I think you know where are that words are.
I still keep the translation of the control panel.

I am very happy to hear that you will use my translation file.☺️
Hope you will soon to work out this problem！

Sorry to my poor English, i am just a new Senior high Grade One student, hope that you can understand what i want to express. 😉

**Comment by UnhappyCodings** [comment]
I found the problem, just need to found a solution too!
Would be happy to use your file! And dont worry, my english isnt the best either, im from germany ^^

**Comment by zirrsm322** [comment]
> I found the problem, just need to found a solution too! Would be happy to use your file! And dont worry, my english isnt the best either, im from germany ^^

Hope you soon to find out the way to slove！ Good luck！

**Comment by UnhappyCodings** [comment]
Hey! Its me again, could you tell me if the fonts size is good? Is it readable? I managed to use the default minecraft font for unicode characters.
(Ignore the weird characters in the middle part)
![image](https://github.com/UnhappyCodings/thoriumreactors/assets/49205934/6d47aeab-0d96-4faf-a82a-e70a0f02422d)

**Comment by zirrsm322** [comment]
> Hey! Its me again, could you tell me if the fonts size is good? Is it readable? I managed to use the default minecraft font for unicode characters. (Ignore the weird characters in the middle part) ![image](https://private-user-images.githubusercontent.com/49205934/285643516-6d47aeab-0d96-4faf-a82a-e70a0f02422d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTUzMDMsIm5iZiI6MTcwMDk5NTAwMywicGF0aCI6Ii80OTIwNTkzNC8yODU2NDM1MTYtNmQ0N2FlYWItMGQ5Ni00ZmFmLWE4MmEtZTcwYTBmMDI0MjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEwMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMTcyNTgxYWYwZGI0MWVhOWI4YTRiNTgwYWYwZDAzNzUxYmRlYzJhNWFkY2M4YTg0N2U2ZmE1NDZhNjk3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nkyyDfCvx0fQ3jqUgZaif5ERHOqmD2Jtm07PSN9Rbow)

That looks very good! This size is suitable!

But some words seem to like wrong, i will soon to change thhe wrong words and at that time i will send you fixed version!

**Comment by UnhappyCodings** [comment]
![image](https://github.com/UnhappyCodings/thoriumreactors/assets/49205934/c5fa48f6-8a07-4fc4-8aa2-3a8b536100be)
Here's a better view of your translation, does it also fit with the text in the middle part on the top left?

**Comment by zirrsm322** [comment]
> ![image](https://private-user-images.githubusercontent.com/49205934/285644961-c5fa48f6-8a07-4fc4-8aa2-3a8b536100be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTU5MTcsIm5iZiI6MTcwMDk5NTYxNywicGF0aCI6Ii80OTIwNTkzNC8yODU2NDQ5NjEtYzVmYTQ4ZjYtOGEwNy00ZmM0LThhYTItM2E4YjUzNjEwMGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEwNDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNWEwYjU0ZThmNTcyNmEwMTBmYmRhZjU0MTUzNDc0NWM4NTllYjU0NGFkNTVkYzZmMjQ5MDg3NzYwOTAxMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VyDKFh2Q2rf9oxSHym2R1u9VN9TD102cs9fP9Crn7Hc) Here's a better view of your translation, does it also fit with the text in the middle part on the top left?

It is prety a good looking, then it is my work on fix wrong words!

**Comment by UnhappyCodings** [comment]
Good, i will add this to the next beta fix 0.4b, probably coming online today ^^ 
Are you really sure that the space between two words is enough? They are lapping over each other a bit

**Comment by zirrsm322** [comment]
> Good, i will add this to the next beta fix 0.4b, probably coming online today ^^ Are you really sure that the space between two words is enough? They are lapping over each other a bit

Ehh, in fact, in our Chinese writing, this space between two words is very correct.

**Comment by UnhappyCodings** [comment]
Okay lol, i meant the vertical spacing between two lines. (Image)
![image](https://github.com/UnhappyCodings/thoriumreactors/assets/49205934/d88d81da-7473-48a2-b306-3cafea636bdc)

**Comment by zirrsm322** [comment]
> Okay lol, i meant the vertical spacing between two lines. (Image) ![image](https://private-user-images.githubusercontent.com/49205934/285668562-d88d81da-7473-48a2-b306-3cafea636bdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNTk5MDQsIm5iZiI6MTcwMTA1OTYwNCwicGF0aCI6Ii80OTIwNTkzNC8yODU2Njg1NjItZDg4ZDgxZGEtNzQ3My00OGEyLWIzMDYtM2NhZmVhNjM2YmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA0MzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhN2I1MzRmY2IwZjIxMjI2MDQ4ZTVkMWM2OTIzM2Q1NmI2MWI2MWRmMGUwNDBjODg2MWMzZWY2ODY0ZjhlYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ekUWeewxyTB9gXd1grf2zWCgenjgFA2IWe_ppWrrwKs)

It isn't a very big problem, or maybe you can move up a little and make it looks good.

**Comment by zirrsm322** [comment]
> Okay lol, i meant the vertical spacing between two lines. (Image) ![image](https://private-user-images.githubusercontent.com/49205934/285668562-d88d81da-7473-48a2-b306-3cafea636bdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzA3MTgsIm5iZiI6MTcwMTE3MDQxOCwicGF0aCI6Ii80OTIwNTkzNC8yODU2Njg1NjItZDg4ZDgxZGEtNzQ3My00OGEyLWIzMDYtM2NhZmVhNjM2YmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMjAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNjQzMzJmMTUxOWM1YTdkMTEyMThhMmFhZGM5MGJhMzA0OTA4MGFiMjc2N2M5NmQyZTM2MzZjNmU3MzUzYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eDKztPlmhODSG1Cx7jJvoEuYagJmZV_GsydfF9F5qlQ)

Maybe in couple weeks i will send you the fixed lang file, cuz i am busy with school, so it might be a little late

**Comment by UnhappyCodings** [comment]
Yeah, no problem, take your time, will keep this issue open as long as you need ^^ :D

**Comment by UnhappyCodings** [comment]
Hey! Any new progress on the language file? Will make a new version release in the next day(s). :D

**Comment by zirrsm322** [comment]
> Hey! Any new progress on the language file? Will make a new version release in the next day(s). :D

These days i got a flu and school is busy, maybe finished it when the winter vacation came？

**Comment by UnhappyCodings** [comment]
Its me again, will add this in the next version 0.1.6b finally!

**Comment by zirrsm322** [comment]
There it is, the fixed text file
[zh_cn.json](https://github.com/IntelligenceModding/thoriumreactors/files/14195463/zh_cn.json)

**Comment by zirrsm322** [comment]
Sorry for such a long time no replying to you, and it seems like i catch up before 0.1.6b update!
Happy new year to you!

**Comment by zirrsm322** [comment]
> Its me again, will add this in the next version 0.1.6b finally!

Hello my friend! Have you seen the fixed file? You are not reply to me so I want to say hello and remind you!

**Comment by UnhappyCodings** [comment]
Hey! Yeah saw your file and also directly added it into my dev environment, just current short on time for releasing an update!
