### ISSUE TITLE
[Recipe issue] Wrong input on Deepslate Manganese Ore recipe

### ISSUE THREAD

**Issue by DevDyna** [UnhappyCodings/thoriumreactors#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## pressing key 'use' on it [from jei]
![2023-11-29_00 29 10](https://github.com/UnhappyCodings/thoriumreactors/assets/78147916/983fb0bd-d169-4617-8313-eb20239e0e18)

## differents recipe ids on two recipes with same I/O
![2023-11-29_00 30 30](https://github.com/UnhappyCodings/thoriumreactors/assets/78147916/6e6fce19-f866-4d3b-98d0-d0bdb004e805)

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

thoriumreactors-1.20.1-0.1.3.1b-all

### Minecraft Version

1.20.1

### Forge Version

47.2.4

**Comment by UnhappyCodings** [comment]
Hey! Thank you for your report on this. Looks like a simple mistake to me. Will fix that in the next release!

**Comment by UnhappyCodings** [comment]
Took a look and found the problem, will be fixed in 0.1.4b. Thanks!
