### ISSUE TITLE
weird issue with the fluid tanks, and item info

### ISSUE THREAD

**Issue by Nostalgion** [UnhappyCodings/thoriumreactors#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

hovering over the item slots in the fluid tank gui doesnt highlight them, they overall seem broken. there is also an issue with hovering over items for info, ctrl and shift do not function to expand info. version 0.1.3.1b-all on 1.20.1, made sure to replicate the issue with no other mods but this one and fusion

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

other

### Minecraft Version

1.20.1

### Forge Version

40.2.0

**Comment by UnhappyCodings** [comment]
Hey! Thanks for your report. Took a look and found the problem, both will be fixed in 0.1.4b. Thanks!
